# Generated by Django 6.0 on 2026-03-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
